package com.redgrapefruit.utopia.registry

import com.redgrapefruit.utopia.EDIBLE_1
import com.redgrapefruit.utopia.EDIBLE_3
import com.redgrapefruit.utopia.YUCK
import com.redgrapefruit.utopia.util.Module
import com.redgrapefruit.utopia.util.configureFood
import com.redgrapefruit.utopia.util.addComponent
import com.redgrapefruit.utopia.util.moduleSpecific

/**
 * A registry containing all of the mod's patches
 */
object PatchRegistry {
    fun run() {
        // Common FoodComponent patches
        addComponent("hops", "croptopia", EDIBLE_1)
        addComponent("mustard", "croptopia", YUCK)
        addComponent("vanilla", "croptopia", YUCK)
        addComponent("paprika", "croptopia", EDIBLE_1)
        addComponent("chile_pepper", "croptopia", EDIBLE_3)
        addComponent("turmeric", "croptopia", EDIBLE_1)
        addComponent("ginger", "croptopia", EDIBLE_3)
        addComponent("olive_oil", "croptopia", YUCK)
        addComponent("flour", "croptopia", YUCK)
        addComponent("noodle", "croptopia", EDIBLE_1)
        addComponent("molasses", "croptopia", YUCK)
        addComponent("caramel", "croptopia", EDIBLE_1)
        addComponent("soy_sauce", "croptopia", YUCK)
        addComponent("dough", "croptopia", YUCK)
        addComponent("ravioli", "croptopia", EDIBLE_1)
        addComponent("cinnamon", "croptopia", EDIBLE_1)
        addComponent("pepper", "croptopia", EDIBLE_3)
        addComponent("milk_bottle", "croptopia", EDIBLE_1)

        // Realism patches
        moduleSpecific(Module.REALISM) {
            configureFood("almond", "croptopia", ItemRegistry.OVERDUE_ALMOND)
            configureFood("almond_brittle", "croptopia", ItemRegistry.OVERDUE_ALMOND_BRITTLE)
            configureFood("apple_juice", "croptopia", ItemRegistry.OVERDUE_APPLE_JUICE)
            configureFood("apple_pie", "croptopia", ItemRegistry.OVERDUE_APPLE_PIE)
            configureFood("apricot", "croptopia", ItemRegistry.OVERDUE_APRICOT)
            configureFood("apricot_jam", "croptopia", ItemRegistry.OVERDUE_APRICOT_JAM)
            configureFood("artichoke", "croptopia", ItemRegistry.OVERDUE_ARTICHOKE)
            configureFood("artichoke_dip", "croptopia", ItemRegistry.OVERDUE_ARTICHOKE_DIP)
            configureFood("asparagus", "croptopia", ItemRegistry.OVERDUE_ASPARAGUS)
            configureFood("avocado", "croptopia", ItemRegistry.OVERDUE_AVOCADO)
            configureFood("baked_beans", "croptopia", ItemRegistry.OVERDUE_BAKED_BEANS)
            configureFood("banana", "croptopia", ItemRegistry.OVERDUE_BANANA)
            configureFood("banana_cream_pie", "croptopia", ItemRegistry.OVERDUE_BANANA_CREAM_PIE)
            configureFood("banana_nut_bread", "croptopia", ItemRegistry.OVERDUE_BANANA_NUT_BREAD)
            configureFood("barley", "croptopia", ItemRegistry.OVERDUE_BARLEY)
            configureFood("basil", "croptopia", ItemRegistry.OVERDUE_BASIL)
            configureFood("beef_jerky", "croptopia", ItemRegistry.ROTTEN_BEEF_JERKY)
            configureFood("beef_wellington", "croptopia", ItemRegistry.ROTTEN_BEEF_WELLINGTON)
            configureFood("bellpepper", "croptopia", ItemRegistry.OVERDUE_BELLPEPPER)
            configureFood("blackbean", "croptopia", ItemRegistry.OVERDUE_BLACKBEAN)
            configureFood("blackberry", "croptopia", ItemRegistry.OVERDUE_BLACKBERRY)
            configureFood("blackberry_jam", "croptopia", ItemRegistry.OVERDUE_BLACKBERRY_JAM)
            configureFood("blt", "croptopia", ItemRegistry.OVERDUE_BLT)
            configureFood("blueberry", "croptopia", ItemRegistry.OVERDUE_BLUEBERRY)
            configureFood("blueberry_jam", "croptopia", ItemRegistry.OVERDUE_BLUEBERRY_JAM)
            configureFood("broccoli", "croptopia", ItemRegistry.OVERDUE_BROCCOLI)
            configureFood("brownies", "croptopia", ItemRegistry.OVERDUE_BROWNIES)
            configureFood("burrito", "croptopia", ItemRegistry.OVERDUE_BURRITO)
            configureFood("butter", "croptopia", ItemRegistry.OVERDUE_BUTTER)
            configureFood("buttered_toast", "croptopia", ItemRegistry.OVERDUE_BUTTERED_TOAST)
            configureFood("cabbage", "croptopia", ItemRegistry.OVERDUE_CABBAGE)
            configureFood("caesar_salad", "croptopia", ItemRegistry.OVERDUE_CAESAR_SALAD)
            configureFood("candied_nuts", "croptopia", ItemRegistry.OVERDUE_CANDIED_NUTS)
            configureFood("candy_corn", "croptopia", ItemRegistry.OVERDUE_CANDY_CORN)
            configureFood("caramel", "croptopia", ItemRegistry.OVERDUE_CARAMEL)
            configureFood("cantaloupe", "croptopia", ItemRegistry.OVERDUE_CANTALOUPE)
            configureFood("carnitas", "croptopia", ItemRegistry.OVERDUE_CARNITAS)
            configureFood("cashew", "croptopia", ItemRegistry.OVERDUE_CASHEW)
            configureFood("cashew_chicken", "croptopia", ItemRegistry.OVERDUE_CASHEW_CHICKEN)
            configureFood("cauliflower", "croptopia", ItemRegistry.OVERDUE_CAULIFLOWER)
            configureFood("celery", "croptopia", ItemRegistry.OVERDUE_CELERY)
            configureFood("cheese", "croptopia", ItemRegistry.OVERDUE_CHEESE)
            configureFood("cheese_cake", "croptopia", ItemRegistry.OVERDUE_CHEESE_CAKE)
            configureFood("cheese_pizza", "croptopia", ItemRegistry.OVERDUE_CHEESE_PIZZA)
            configureFood("cheeseburger", "croptopia", ItemRegistry.OVERDUE_CHEESEBURGER)
            configureFood("cherry", "croptopia", ItemRegistry.OVERDUE_CHERRY)
            configureFood("cherry_jam", "croptopia", ItemRegistry.OVERDUE_CHERRY_JAM)
            configureFood("cherry_pie", "croptopia", ItemRegistry.OVERDUE_CHERRY_PIE)
            configureFood("chicken_and_dumplings", "croptopia", ItemRegistry.OVERDUE_CHICKEN_AND_DUMPLINGS)
            configureFood("chicken_and_noodles", "croptopia", ItemRegistry.OVERDUE_CHICKEN_AND_NOODLES)
            configureFood("chicken_and_rice", "croptopia", ItemRegistry.OVERDUE_CHICKEN_AND_RICE)
            configureFood("chile_pepper", "croptopia", ItemRegistry.OVERDUE_CHILE_PEPPER)
            configureFood("chili_relleno", "croptopia", ItemRegistry.OVERDUE_CHILI_RELLENO)
            configureFood("chimichanga", "croptopia", ItemRegistry.OVERDUE_CHIMICHANGA)
            configureFood("chocolate", "croptopia", ItemRegistry.OVERDUE_CHOCOLATE)
            configureFood("chocolate_milkshake", "croptopia", ItemRegistry.OVERDUE_CHOCOLATE_MILKSHAKE)
            configureFood("cinnamon", "croptopia", ItemRegistry.OVERDUE_CINNAMON)
            configureFood("coconut", "croptopia", ItemRegistry.OVERDUE_COCONUT)
            configureFood("coffee", "croptopia", ItemRegistry.OVERDUE_COFFEE)
            configureFood("coffee_beans", "croptopia", ItemRegistry.OVERDUE_COFFEE_BEANS)
            configureFood("corn", "croptopia", ItemRegistry.OVERDUE_CORN)
            configureFood("cornish_pasty", "croptopia", ItemRegistry.OVERDUE_CORNISH_PASTY)
            configureFood("cranberry", "croptopia", ItemRegistry.OVERDUE_CRANBERRY)
            configureFood("cranberry_juice", "croptopia", ItemRegistry.OVERDUE_CRANBERRY_JUICE)
            configureFood("crema", "croptopia", ItemRegistry.OVERDUE_CREMA)
            configureFood("cucumber", "croptopia", ItemRegistry.OVERDUE_CUCUMBER)
            configureFood("cucumber_salad", "croptopia", ItemRegistry.OVERDUE_CUCUMBER_SALAD)
            configureFood("currant", "croptopia", ItemRegistry.OVERDUE_CURRANT)
            configureFood("date", "croptopia", ItemRegistry.OVERDUE_DATE)
            configureFood("dough", "croptopia", ItemRegistry.OVERDUE_DOUGH)
            configureFood("doughnut", "croptopia", ItemRegistry.OVERDUE_DOUGHNUT)
            configureFood("dragonfruit", "croptopia", ItemRegistry.OVERDUE_DRAGONFRUIT)
            configureFood("egg_roll", "croptopia", ItemRegistry.OVERDUE_EGG_ROLL)
            configureFood("eggplant", "croptopia", ItemRegistry.OVERDUE_EGGPLANT)
            configureFood("elderberry", "croptopia", ItemRegistry.OVERDUE_ELDERBERRY)
            configureFood("elderberry_jam", "croptopia", ItemRegistry.OVERDUE_ELDERBERRY_JAM)
            configureFood("enchilada", "croptopia", ItemRegistry.OVERDUE_ENCHILADA)
            configureFood("eton_mess", "croptopia", ItemRegistry.OVERDUE_ETON_MESS)
            configureFood("fajitas", "croptopia", ItemRegistry.OVERDUE_FAJITAS)
            configureFood("fig", "croptopia", ItemRegistry.OVERDUE_FIG)
            configureFood("figgy_pudding", "croptopia", ItemRegistry.OVERDUE_FIGGY_PUDDING)
            configureFood("fish_and_chips", "croptopia", ItemRegistry.OVERDUE_FISH_AND_CHIPS)
            configureFood("flour", "croptopia", ItemRegistry.OVERDUE_FLOUR)
            configureFood("french_fries", "croptopia", ItemRegistry.OVERDUE_FRENCH_FRIES)
            configureFood("fried_chicken", "croptopia", ItemRegistry.ROTTEN_FRIED_CHICKEN)
            configureFood("fruit_salad", "croptopia", ItemRegistry.OVERDUE_FRUIT_SALAD)
            configureFood("fruit_smoothie", "croptopia", ItemRegistry.OVERDUE_FRUIT_SMOOTHIE)
            configureFood("garlic", "croptopia", ItemRegistry.OVERDUE_GARLIC)
            configureFood("ginger", "croptopia", ItemRegistry.OVERDUE_GINGER)
            configureFood("grape", "croptopia", ItemRegistry.OVERDUE_GRAPE)
            configureFood("grape_jam", "croptopia", ItemRegistry.OVERDUE_GRAPE_JAM)
            configureFood("grapefruit", "croptopia", ItemRegistry.OVERDUE_GRAPEFRUIT)
            configureFood("greenbean", "croptopia", ItemRegistry.OVERDUE_GREENBEAN)
            configureFood("greenonion", "croptopia", ItemRegistry.OVERDUE_GREENONION)
            configureFood("grilled_cheese", "croptopia", ItemRegistry.OVERDUE_GRILLED_CHEESE)
            configureFood("ham_sandwich", "croptopia", ItemRegistry.OVERDUE_HAM_SANDWICH)
            configureFood("hamburger", "croptopia", ItemRegistry.OVERDUE_HAMBURGER)
            configureFood("hops", "croptopia", ItemRegistry.OVERDUE_HOPS)
            configureFood("horchata", "croptopia", ItemRegistry.OVERDUE_HORCHATA)
            configureFood("kale", "croptopia", ItemRegistry.OVERDUE_KALE)
            configureFood("kale_chips", "croptopia", ItemRegistry.OVERDUE_KALE_CHIPS)
            configureFood("kale_smoothie", "croptopia", ItemRegistry.OVERDUE_KALE_SMOOTHIE)
            configureFood("kiwi", "croptopia", ItemRegistry.OVERDUE_KIWI)
            configureFood("kumquat", "croptopia", ItemRegistry.OVERDUE_KUMQUAT)
            configureFood("leafy_salad", "croptopia", ItemRegistry.OVERDUE_LEAFY_SALAD)
            configureFood("leek", "croptopia", ItemRegistry.OVERDUE_LEEK)
            configureFood("leek_soup", "croptopia", ItemRegistry.OVERDUE_LEEK_SOUP)
            configureFood("lemon", "croptopia", ItemRegistry.OVERDUE_LEMON)
            configureFood("lemon_chicken", "croptopia", ItemRegistry.ROTTEN_LEMON_CHICKEN)
            configureFood("lemonade", "croptopia", ItemRegistry.OVERDUE_LEMONADE)
            configureFood("lettuce", "croptopia", ItemRegistry.OVERDUE_LETTUCE)
            configureFood("lime", "croptopia", ItemRegistry.OVERDUE_LIME)
            configureFood("limeade", "croptopia", ItemRegistry.OVERDUE_LIMEADE)
            configureFood("mango", "croptopia", ItemRegistry.OVERDUE_MANGO)
            configureFood("mango_ice_cream", "croptopia", ItemRegistry.OVERDUE_MANGO_ICE_CREAM)
            configureFood("mead", "croptopia", ItemRegistry.OVERDUE_MEAD)
            configureFood("melon_juice", "croptopia", ItemRegistry.OVERDUE_MELON_JUICE)
            configureFood("milk_bottle", "croptopia", ItemRegistry.OVERDUE_MILK_BOTTLE)
            configureFood("molasses", "croptopia", ItemRegistry.OVERDUE_MOLASSES)
            configureFood("mustard", "croptopia", ItemRegistry.OVERDUE_MUSTARD)
            configureFood("nectarine", "croptopia", ItemRegistry.OVERDUE_NECTARINE)
            configureFood("noodle", "croptopia", ItemRegistry.OVERDUE_NECTARINE)
            configureFood("nougat", "croptopia", ItemRegistry.OVERDUE_NOUGAT)
            configureFood("nutmeg", "croptopia", ItemRegistry.OVERDUE_NUTMEG)
            configureFood("nutty_cookie", "croptopia", ItemRegistry.OVERDUE_NUTTY_COOKIE)
            configureFood("oat", "croptopia", ItemRegistry.OVERDUE_OAT)
            configureFood("oatmeal", "croptopia", ItemRegistry.OVERDUE_OATMEAL)
            configureFood("olive", "croptopia", ItemRegistry.OVERDUE_OLIVE)
            configureFood("olive_oil", "croptopia", ItemRegistry.OVERDUE_OLIVE_OIL)
            configureFood("onion", "croptopia", ItemRegistry.OVERDUE_ONION)
            configureFood("onion_rings", "croptopia", ItemRegistry.OVERDUE_ONION_RINGS)
            configureFood("orange", "croptopia", ItemRegistry.OVERDUE_ORANGE)
            configureFood("orange_juice", "croptopia", ItemRegistry.OVERDUE_ORANGE_JUICE)
            configureFood("paprika", "croptopia", ItemRegistry.OVERDUE_PAPRIKA)
            configureFood("peach", "croptopia", ItemRegistry.OVERDUE_PEACH)
            configureFood("peach_jam", "croptopia", ItemRegistry.OVERDUE_PEACH_JAM)
            configureFood("peanut", "croptopia", ItemRegistry.OVERDUE_PEANUT)
            configureFood("peanut_butter_and_jam", "croptopia", ItemRegistry.OVERDUE_PEANUT_BUTTER_AND_JAM)
            configureFood("pear", "croptopia", ItemRegistry.OVERDUE_PEAR)
            configureFood("pecan", "croptopia", ItemRegistry.OVERDUE_PECAN)
            configureFood("pecan_ice_cream", "croptopia", ItemRegistry.OVERDUE_PECAN_ICE_CREAM)
            configureFood("pecan_pie", "croptopia", ItemRegistry.OVERDUE_PECAN_PIE)
            configureFood("pepper", "croptopia", ItemRegistry.OVERDUE_PEPPER)
            configureFood("pepperoni", "croptopia", ItemRegistry.OVERDUE_PEPPERONI)
            configureFood("persimmon", "croptopia", ItemRegistry.OVERDUE_PERSIMMON)
            configureFood("pineapple", "croptopia", ItemRegistry.OVERDUE_PINEAPPLE)
            configureFood("pineapple_juice", "croptopia", ItemRegistry.OVERDUE_PINEAPPLE_JUICE)
            configureFood("pineapple_pepperoni_pizza", "croptopia", ItemRegistry.OVERDUE_PINEAPPLE_PEPPERONI_PIZZA)
            configureFood("pizza", "croptopia", ItemRegistry.OVERDUE_PIZZA)
            configureFood("plum", "croptopia", ItemRegistry.OVERDUE_PLUM)
            configureFood("popcorn", "croptopia", ItemRegistry.OVERDUE_POPCORN)
            configureFood("pork_and_beans", "croptopia", ItemRegistry.OVERDUE_PORK_AND_BEANS)
            configureFood("pork_jerky", "croptopia", ItemRegistry.ROTTEN_PORK_JERKY)
            configureFood("potato_chips", "croptopia", ItemRegistry.OVERDUE_POTATO_CHIPS)
            configureFood("protein_bar", "croptopia", ItemRegistry.OVERDUE_PROTEIN_BAR)
        }
    }
}